version: '3'

services:
  db:
    image: mysql:8.0.23
    container_name: db
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - "3306:3306"
    volumes:
        - ./db/data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./db/init:/docker-entrypoint-initdb.d
